POST http://localhost:3001/character
Content-Type: application/json

{
    "image": "",
    "name": "coucou",
    "level": "coucou",
    "race": "coucou",
    "job": "coucou",
    "age": "coucou",
    "taille": "coucou",
    "pv": "coucou",
    "armor": "coucou",
    "initiative": "coucou",
    "strength": "coucou",
    "dexterity": "coucou",
    "constitution": "coucou",
    "intelligence": "coucou",
    "wisdow": "coucou",
    "charisma": "coucou",
    "feats": "coucou",
    "skill": "coucou",
    "languages": "coucou",
    "knowlegde": "coucou"
}

################
GET http://localhost:3001/character/3
Content-Type: application/json

################
DELETE http://localhost:3001/character/3
Content-Type: application/json

################
GET http://localhost:3001/character/3/36
Content-Type: application/json

################
POST http://localhost:3001/register
Content-Type: application/json

{
  "username": "toto",
  "email": "toto@gmail.com",
  "password": "rootroot"
  }